// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr4ljeuazsbS01l0uo-kymePHCpfmE8TU',
    appId: '1:451910131985:web:bf447fb4af252c6306acb0',
    messagingSenderId: '451910131985',
    projectId: 'fintech-2b254',
    authDomain: 'fintech-2b254.firebaseapp.com',
    storageBucket: 'fintech-2b254.appspot.com',
    measurementId: 'G-LRQ9HK5T05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGQWzfbGDosKYBppN607k69h9tlSemS0',
    appId: '1:451910131985:android:46aa2ff287837d8006acb0',
    messagingSenderId: '451910131985',
    projectId: 'fintech-2b254',
    storageBucket: 'fintech-2b254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtk916-pcYWVsuuljnR-HEgmBKFUAfMDs',
    appId: '1:451910131985:ios:6afe76d94c47a9c306acb0',
    messagingSenderId: '451910131985',
    projectId: 'fintech-2b254',
    storageBucket: 'fintech-2b254.appspot.com',
    iosClientId: '451910131985-07cl3hsd0i7culf1cgimn3p56h488rai.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtk916-pcYWVsuuljnR-HEgmBKFUAfMDs',
    appId: '1:451910131985:ios:6afe76d94c47a9c306acb0',
    messagingSenderId: '451910131985',
    projectId: 'fintech-2b254',
    storageBucket: 'fintech-2b254.appspot.com',
    iosClientId: '451910131985-07cl3hsd0i7culf1cgimn3p56h488rai.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr4ljeuazsbS01l0uo-kymePHCpfmE8TU',
    appId: '1:451910131985:web:90bce5e66fdc64fe06acb0',
    messagingSenderId: '451910131985',
    projectId: 'fintech-2b254',
    authDomain: 'fintech-2b254.firebaseapp.com',
    storageBucket: 'fintech-2b254.appspot.com',
    measurementId: 'G-SK2HDLRN29',
  );

}